# Generated by Django 4.0.4 on 2022-05-31 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='email користувача')),
                ('name', models.CharField(max_length=30, verbose_name='email користувача')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль користувача')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.user')),
                ('wallet', models.CharField(max_length=150, verbose_name='Гаманець користувача')),
                ('Tron', models.FloatField(default='0', verbose_name='Кількість Tron на гаманці')),
                ('Avira', models.FloatField(default='0', verbose_name='Кількість Avira на гаманці')),
                ('USDT', models.FloatField(default='0', verbose_name='Кількість USDT на гаманці')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=150, verbose_name='Гаманець користувача')),
                ('DateTime', models.DateTimeField(verbose_name='Дата та час транзакції')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
