# Generated by Django 4.0.4 on 2022-05-31 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Users'},
        ),
    ]
