# Generated by Django 4.0.4 on 2022-06-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_history_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('wallet_from', models.CharField(max_length=150, verbose_name='З гаманеця користувача')),
                ('wallet_in', models.CharField(max_length=150, verbose_name='В гаманець користувача')),
                ('DateTime', models.DateTimeField(verbose_name='Дата та час транзакції')),
                ('count', models.CharField(max_length=50, verbose_name='Кількість токенів')),
            ],
        ),
    ]
